### ISSUE TITLE
自動更新のデータ保存がいつまでたっても終わらないことがある

### ISSUE THREAD

**Issue by kmycode** [kmycode/kmy-keiba#243]
![image](https://github.com/kmycode/kmy-keiba/assets/13672783/a00a64b6-18ed-42f9-b4b9-fe71f76f2274)

おそらく`SetTask`でのデータ書き込みが成功するまでどこかで監視してるかもしれない

```
2024-05-05 19:53:02,487 [1] (28776) INFO  JVLinkLoader - ロード処理が正常に完了しました
2024-05-05 19:53:02,488 [1] (28776) INFO  JVLinkLoader - ロードが完了しました
2024-05-05 19:53:02,488 [1] (28776) INFO  JVLinkLoader - 接続を終了します
2024-05-05 19:53:02,488 [1] (28776) INFO  JVLinkLoader - 接続は終了しました
2024-05-05 19:53:02,758 [11] (28776) ERROR Program - タスクへのデータ書き込みに失敗しました
System.AggregateException: One or more errors occurred. (An error occurred while saving the entity changes. See the inner exception for details.)
 ---> Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteDataRecord.Dispose()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at System.Data.Common.DbDataReader.NextResultAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at KmyKeiba.Downloader.MyContext.SaveChangesAsync() in C:\Users\tt\Documents\repo\KmyKeiba\KmyKeiba.Downloader\MyContext.cs:line 41
   at KmyKeiba.Downloader.MyContext.<SaveChanges>b__4_0() in C:\Users\tt\Documents\repo\KmyKeiba\KmyKeiba.Downloader\MyContext.cs:line 63
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.get_Result()
   at KmyKeiba.Downloader.MyContext.SaveChanges() in C:\Users\tt\Documents\repo\KmyKeiba\KmyKeiba.Downloader\MyContext.cs:line 63
   at KmyKeiba.Downloader.Program.SetTask(DownloaderTaskData task, Action`1 changes) in C:\Users\tt\Documents\repo\KmyKeiba\KmyKeiba.Downloader\Program.cs:line 428
```

**Comment by kmycode** [comment]
ダウンローダで`CheckShutdown`メソッド内で

- アプリとの連携方法がDBからファイルに変わったのだが、まだDBに書き込みする処理が残っていた
- このメソッドの呼び出し側で、ファイル読み込めないときの例外を適切に処理できていない箇所があった

のを修正し、現在発生が確認できないのでクローズとします
